on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  go-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      TF_VAR_auth0_tenant_domain: test.eu.auth0.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
          terraform_wrapper: false

      - name: Run terraform Tests
        working-directory: examples/
        run: |
          terraform init
          terraform validate
